name: Check

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -D warnings

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: awalsh128/cache-apt-pkgs-action@5513791f75b039e2a79653b1a92238d3fb8d99b4
        with:
          packages: tshark
          version: 1.0

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          submodules: recursive
          persist-credentials: false
      - uses: moonrepo/setup-rust@abb2d32350334249b178c401e5ec5836e0cd88d3
      - name: Test
        run: cargo test

  pre-commit:
    name: Run pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          submodules: recursive
          persist-credentials: false
      - uses: moonrepo/setup-rust@abb2d32350334249b178c401e5ec5836e0cd88d3
        with:
          components: clippy,rustfmt
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd
