name: Check

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -D warnings

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: awalsh128/cache-apt-pkgs-action@acb598e5ddbc6f68a970c5da0688d2f3a9f04d05
        with:
          packages: tshark
          version: 1.0

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          submodules: recursive
          persist-credentials: false
      - uses: moonrepo/setup-rust@abb2d32350334249b178c401e5ec5836e0cd88d3
      - name: Test
        run: cargo test

  pre-commit:
    name: Run pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          submodules: recursive
          persist-credentials: false
      - uses: moonrepo/setup-rust@abb2d32350334249b178c401e5ec5836e0cd88d3
        with:
          components: clippy,rustfmt
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd
