name: Check

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -D warnings

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: tshark
          version: 1.0

      - uses: actions/checkout@v5
        with:
          submodules: recursive
          persist-credentials: false
      - uses: moonrepo/setup-rust@v1
      - name: Test
        run: cargo test

  pre-commit:
    name: Run pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
          persist-credentials: false
      - uses: moonrepo/setup-rust@v1
      - uses: actions/setup-python@v6
      - uses: pre-commit/action@v3.0.1
